on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: Chryz-Hub
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<p><b>Invitation sent for the GitHub Organisation. Welcome to the community 🎉</p></b>An invitation request has been sent to your GitHUb registered E-mail, so accept it now to join the community because it expires. Do not forget to join us via<ul><li><a href="https://discord.gg/c6RhGwcP5b">Discord channel</a></li><li><a href="https://www.youtube.com/channel/UCEoxZzYHN1c9ISazmxeCtCQ">Youtube channel</a> by subscribing</li><li><a href="https://twitter.com/ChryzHub">Twitter</a><li><a href="https://github.com/chryz-hub">GitHub organization</a> by raising an <a href="https://github.com/chryz-hub/chryz-hub.github.io/issues/new?assignees=&labels=invite+me+to+the+organization&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization">invitational issue</a></li></ul>and make your <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/membership-visibility.md">membership visibility public</a> and also add your name been a contributor/member of the community <a href="https://github.com/chryz-hub/chryz-hub.github.io/blob/master/CONTRIBUTORS.md">here</a>.</p> <b>Do you want to make connections or your first pull request, we got you covered!</b> Make this <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/My-PR-Contribution-Practice.md">pull request</a> and also get a green square 🟩 for free😅.</a><p> Do not forget, open-source is beyond coding but the coming together of people, ideas, communicating, adding values and solving problems.</p><b>We hope this set you for the open-source journey ahead!</b>'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
